// Set User
export const SET_USER__SUCCESS = 'SET_USER__SUCCESS';

// Clear user
export const CLEAR_USER = 'CLEAR_USER';

// Send message
export const SEND_MESSAGE__REQUEST = 'SEND_MESSAGE__REQUEST';
export const SEND_MESSAGE__SUCCESS = 'SEND_MESSAGE__SUCCESS';
export const SEND_MESSAGE__FAILURE = 'SEND_MESSAGE__FAILURE';

// Get get messages
export const GRAB_MESSAGES__REQUEST = 'GRAB_MESSAGES__REQUEST';
export const GRAB_MESSAGES__SUCCESS = 'GRAB_MESSAGES__SUCCESS';
export const GRAB_MESSAGES__FAILURE = 'GRAB_MESSAGES__FAILURE';
